# Generated by Django 6.0.4 on 2026-05-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
