# Generated by Django 6.0.4 on 2026-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='view',
            field=models.IntegerField(default=10),
        ),
    ]
