# Generated by Django 6.0.4 on 2026-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articles_slug_alter_articles_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, default='default-item', null=True, unique=True),
        ),
    ]
