# Generated by Django 6.0.4 on 2026-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_articles_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Our_team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("skill", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="teams")),
            ],
        ),
        migrations.AlterField(
            model_name="articles",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
