# Generated by Django 6.0.4 on 2026-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_our_team_alter_articles_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="our_team",
            options={"verbose_name": "team", "verbose_name_plural": "teams"},
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
