# Generated by Django 6.0.4 on 2026-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_our_team_options_alter_category_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="our_team",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="our_team",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="teams"),
        ),
    ]
